@baseUrl = http://localhost:3000


# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{  
    "municipio": "Goiania",
    "nome_propr": "Terra",
    "cpf_cnpj": "123456789",
    "proprietar": "Hianka"

}


### 
# @name upload
POST {{baseUrl}}/upload
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="file"; filename="TABELASICAR2024.csv"
Content-Type: text/csv

< ./TABELASICAR2024.csv
--boundary--